# Generated by Django 3.2.6 on 2021-08-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_contacts', '0002_auto_20210821_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContacts',
        ),
    ]
