# Generated by Django 3.2.6 on 2021-08-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imported_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spam_liklihood',
        ),
    ]
