# Generated by Django 3.2.6 on 2021-08-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usercontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContacts',
            new_name='UserContact',
        ),
    ]
