# Generated by Django 3.2.6 on 2021-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_usercontacts_usercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
